### ISSUE TITLE
Add support for unicode characters in testcase

### ISSUE THREAD

**Issue by Akasurde** [SatelliteQE/betelgeuse#78] opened 2016-09-02 11:33 UTC
Seems that betelgeuse fails to parse testcase docstring which contains unicode character

```
1. ipa ca-find é
Traceback (most recent call last):
  File "/data/akasurde/src/betelgeuse/venv/bin/betelgeuse", line 9, in <module>
    load_entry_point('Betelgeuse==0.5.0', 'console_scripts', 'betelgeuse')()
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/data/akasurde/src/betelgeuse/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/betelgeuse.py", line 637, in test_case
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 12: ordinal not in range(128)

```

**Comment by Akasurde** [comment] 2016-09-02 11:50
@omaciel @elyezer  Can you suggest any work around for this issue ?

**Comment by elyezer** [comment] 2017-04-24 21:35
@Akasurde I know it has been a while but do you still face this issue?

I wrote a test:

```python
def test_parse_rst_special_characters():
    """Check if ``parse_rst`` plays nice with special characters."""
    assert parser.parse_rst(u'String with special character like é') == (
        u'<div class="document">\n'
        u'<p>String with special character like é</p>\n'
        u'</div>\n'
    )
```

To check if that was failing and it is working. I can't reproduce it. One advice I have is, make sure that when using special characters on Python 2 that you define the encoding, for example, make this the first module's line:

```python
# coding=utf-8
```

I will submit the test and will close this issue. If you still facing this issue then please send me an email with the test module you are trying to parse.

Thank you

**Closed as completed** 2017-04-24 21:38 UTC
