### ISSUE TITLE
Pytest style parametrization

### ISSUE THREAD

**Issue by mbukatov** [SatelliteQE/betelgeuse#115] opened 2018-07-19 09:22 UTC
Could betelgeuse handle pytest style parametrization, reporting each combination from expanded parametrization matrix as unique test case?

**Comment by elyezer** [comment] 2018-07-24 09:47
Betelgeuse can't do that since it does static code analysis just like a linter. The pytest marks are dynamic, they need to import the code so that decorators are evaluated in order to add those marks.

I've created https://github.com/elyezer/pytest-betelgeuse to do some research on being able to parse the parameters. Unfortunately I got very busy on the other projects that I was not able to get the code ready and pushed. I was able to find the pytest objects needed to provide the parameters information and I now I need to write it down and get it generating the XML importer file.

I will leave this open for now, but this is something that betelgeuse itself can't do.

**Comment by mbukatov** [comment] 2018-07-30 07:10
Thanks for the update. That means I can't use betelgeuse to get my current test case code importable right now.

My plan is to create sphinx autodoc directives which would be able to statically analyze pytest test cases (parsing the python source code into ast and using some pytest functions on top of that) to generate sphinx representation of the test case (in a similar way how autodoc is used to generate documentation for python code). From there, I could plug it into pylatest sphinx extension, which can already generate the xml importer files. In other words, my approach is to use standard upstream frameworks as much as possible (pytest, sphinx) and create plugins for these to get the functionality I miss.

**Comment by elyezer** [comment] 2018-07-31 18:49
@mbukatov I am very close to a release on another project I am working on and I am not able to push the code I have for the pytest-plugin. I will try to get this pushed this or next week.

I will let you know about it.

**Comment by mbukatov** [comment] 2018-07-31 18:57
@elyezer No problem, I can relate to that (I wasn't able to spend much time on writing the plugins as I sketched above neither and so I was looking at betelgeuse as a way to kickstart the import). Thanks for the reply.

**Comment by elyezer** [comment] 2019-10-29 20:25
This issue will be handled by https://github.com/SatelliteQE/betelgeuse/pull/123

**Comment by elyezer** [comment] 2019-11-08 06:02
Closing as duplicate of https://github.com/SatelliteQE/betelgeuse/issues/39

**Closed as completed by elyezer** 2019-11-08 06:02 UTC
